In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')

import warnings
warnings.filterwarnings('ignore')
import re

# 데이터-속성 매칭
### HappyNewYear님의 공유 코드 사용
* https://dacon.io/competitions/official/235863/codeshare/3877?page=1&dtype=recent

In [2]:
d_code = pd.read_csv('./_data/속성_D_코드.csv', index_col=0).T.to_dict()
h_code = pd.read_csv('./_data/속성_H_코드.csv', index_col=0).T.to_dict()
l_code = pd.read_csv('./_data/속성_L_코드.csv', index_col=0).T.to_dict()

t1 = pd.read_csv('./_data/train.csv',index_col=0)
t2 = pd.read_csv('./_data/test.csv',index_col=0)

In [3]:
from typing import Dict
def add_code(
    df: pd.DataFrame,
    d_code: Dict[int, Dict[str, int]], 
    h_code: Dict[int, Dict[str, int]], 
    l_code: Dict[int, Dict[str, int]],
) -> pd.DataFrame:
    
    # Copy input data
    df = df.copy()   

    # D Code
    df['person_prefer_d_1_n'] = df['person_prefer_d_1'].apply(lambda x: d_code[x]['속성 D 세분류코드'])
    df['person_prefer_d_1_s'] = df['person_prefer_d_1'].apply(lambda x: d_code[x]['속성 D 소분류코드'])
    df['person_prefer_d_1_m'] = df['person_prefer_d_1'].apply(lambda x: d_code[x]['속성 D 중분류코드'])
    df['person_prefer_d_1_l'] = df['person_prefer_d_1'].apply(lambda x: d_code[x]['속성 D 대분류코드'])

    df['person_prefer_d_2_n'] = df['person_prefer_d_2'].apply(lambda x: d_code[x]['속성 D 세분류코드'])
    df['person_prefer_d_2_s'] = df['person_prefer_d_2'].apply(lambda x: d_code[x]['속성 D 소분류코드'])
    df['person_prefer_d_2_m'] = df['person_prefer_d_2'].apply(lambda x: d_code[x]['속성 D 중분류코드'])
    df['person_prefer_d_2_l'] = df['person_prefer_d_2'].apply(lambda x: d_code[x]['속성 D 대분류코드'])

    df['person_prefer_d_3_n'] = df['person_prefer_d_3'].apply(lambda x: d_code[x]['속성 D 세분류코드'])
    df['person_prefer_d_3_s'] = df['person_prefer_d_3'].apply(lambda x: d_code[x]['속성 D 소분류코드'])
    df['person_prefer_d_3_m'] = df['person_prefer_d_3'].apply(lambda x: d_code[x]['속성 D 중분류코드'])
    df['person_prefer_d_3_l'] = df['person_prefer_d_3'].apply(lambda x: d_code[x]['속성 D 대분류코드'])

    df['contents_attribute_d_n'] = df['contents_attribute_d'].apply(lambda x: d_code[x]['속성 D 세분류코드'])
    df['contents_attribute_d_s'] = df['contents_attribute_d'].apply(lambda x: d_code[x]['속성 D 소분류코드'])
    df['contents_attribute_d_m'] = df['contents_attribute_d'].apply(lambda x: d_code[x]['속성 D 중분류코드'])
    df['contents_attribute_d_l'] = df['contents_attribute_d'].apply(lambda x: d_code[x]['속성 D 대분류코드'])

    # H Code
    df['person_prefer_h_1_l'] = df['person_prefer_h_1'].apply(lambda x: h_code[x]['속성 H 대분류코드'])
    df['person_prefer_h_1_m'] = df['person_prefer_h_1'].apply(lambda x: h_code[x]['속성 H 중분류코드'])
    
    df['person_prefer_h_2_l'] = df['person_prefer_h_2'].apply(lambda x: h_code[x]['속성 H 대분류코드'])
    df['person_prefer_h_2_m'] = df['person_prefer_h_2'].apply(lambda x: h_code[x]['속성 H 중분류코드'])
    
    df['person_prefer_h_3_l'] = df['person_prefer_h_3'].apply(lambda x: h_code[x]['속성 H 대분류코드'])
    df['person_prefer_h_3_m'] = df['person_prefer_h_3'].apply(lambda x: h_code[x]['속성 H 중분류코드'])

    df['contents_attribute_h_l'] = df['contents_attribute_h'].apply(lambda x: h_code[x]['속성 H 대분류코드'])
    df['contents_attribute_h_m'] = df['contents_attribute_h'].apply(lambda x: h_code[x]['속성 H 중분류코드'])

    # L Code
    df['contents_attribute_l_n'] = df['contents_attribute_l'].apply(lambda x: l_code[x]['속성 L 세분류코드'])
    df['contents_attribute_l_s'] = df['contents_attribute_l'].apply(lambda x: l_code[x]['속성 L 소분류코드'])
    df['contents_attribute_l_m'] = df['contents_attribute_l'].apply(lambda x: l_code[x]['속성 L 중분류코드'])
    df['contents_attribute_l_l'] = df['contents_attribute_l'].apply(lambda x: l_code[x]['속성 L 대분류코드'])
    
    return df

In [44]:
df_train = add_code(t1, d_code, h_code, l_code)
df_test = add_code(t2, d_code, h_code, l_code)

In [45]:
from sklearn.cluster import KMeans

def k_means_features(df,cols:list, k=5):
    X = df[cols]
    SEED = 42
    km = KMeans(n_clusters=k,
               init='k-means++',
               n_init=10,
               max_iter=300,
               tol=1e-04,
               random_state=SEED)
    y_km = km.fit_predict(X)
    df[f'y_km(k{k})'] = y_km
    return km

In [46]:
cluster_cols = ['person_attribute_a','person_attribute_a_1', 'person_attribute_b']

In [47]:
km = k_means_features(df_train, cluster_cols)
df_test['y_km(k5)'] = km.predict(df_test[cluster_cols])

In [29]:
df_train

,d_l_match_yn,d_m_match_yn,d_s_match_yn,h_l_match_yn,h_m_match_yn,h_s_match_yn,person_attribute_a,person_attribute_a_1,person_attribute_b,person_prefer_c,...,person_prefer_h_2_m,person_prefer_h_3_l,person_prefer_h_3_m,contents_attribute_h_l,contents_attribute_h_m,contents_attribute_l_n,contents_attribute_l_s,contents_attribute_l_m,contents_attribute_l_l,y_km_k5
id,,,,,,,,,,,,,,,,,,,,,
0,True,True,True,False,False,False,1,4,3,5,...,398,58,368,94,422,1607,1606,1605,2016,1
1,False,False,False,True,True,False,1,3,4,1,...,400,94,399,94,417,1607,1606,1605,2016,2
2,False,False,False,True,False,False,2,0,3,5,...,528,48,366,48,363,1599,1595,1572,2016,3
3,False,False,False,True,False,False,2,0,2,5,...,495,1,315,71,381,1607,1606,1605,2016,3
4,True,True,True,False,False,False,1,3,4,5,...,481,208,480,71,381,1607,1606,1605,2016,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501946,False,False,False,True,False,False,1,1,2,2,...,316,94,398,58,373,352,347,346,2006,3
501947,True,True,False,True,False,False,1,6,2,1,...,425,94,398,94,425,155,138,99,2006,4
501948,True,True,True,True,False,False,1,7,4,1,...,413,94,422,58,373,437,417,407,2006,4
501949,True,False,False,True,False,False,1,1,2,1,...,359,250,523,250,524,659,652,651,2006,3
501950,True,True,True,True,False,False,1,6,3,5,...,342,48,359,277,548,785,784,759,2006,4

In [37]:
df_test

,d_l_match_yn,d_m_match_yn,d_s_match_yn,h_l_match_yn,h_m_match_yn,h_s_match_yn,person_attribute_a,person_attribute_a_1,person_attribute_b,person_prefer_c,...,person_prefer_h_2_m,person_prefer_h_3_l,person_prefer_h_3_m,contents_attribute_h_l,contents_attribute_h_m,contents_attribute_l_n,contents_attribute_l_s,contents_attribute_l_m,contents_attribute_l_l,y_km(k5)
id,,,,,,,,,,,,,,,,,,,,,
0,True,False,False,True,True,True,1,1,2,1,...,366,48,359,250,528,1146,1128,1021,2010,3
1,False,False,False,True,False,False,2,0,2,2,...,528,48,359,250,528,1610,1606,1605,2016,3
2,True,False,False,True,True,True,2,3,2,1,...,451,169,452,169,453,1812,1811,1810,2020,2
3,True,False,False,True,True,True,1,2,2,5,...,451,169,452,169,453,101,100,99,2006,2
4,True,False,False,True,False,False,1,6,4,5,...,453,3,316,169,453,984,980,954,2009,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46399,True,True,True,False,False,False,2,0,4,1,...,316,94,398,85,396,759,759,759,2006,0
46400,True,False,False,True,False,False,2,0,4,1,...,342,277,542,85,396,759,759,759,2006,0
46401,True,True,False,True,True,True,2,0,3,1,...,543,277,542,277,547,759,759,759,2006,3
46402,True,True,False,True,True,True,1,3,3,2,...,543,277,542,277,547,759,759,759,2006,2
46403,True,True,False,True,True,True,1,2,4,1,...,543,277,543,277,547,759,759,759,2006,2

# 동일한 속성 매칭 및 순서형 데이터 처리
### 열람일시 데이터로 시간, 요일 정보 추가
### 같은 알파벳은 동일한 속성을 의미. 속성 매칭 여부 정보 추가

In [9]:
from sklearn.preprocessing import LabelEncoder

def match_cols(df, del_columns=False):
    
    del_cols = ['person_attribute_a','person_prefer_f','person_prefer_g', 'contents_open_dt', 'person_rn', 'contents_rn']
    
    
    # d속성과 h속성 일치여부
    p_cols = []
    c_d_cols = []
    c_h_cols = []    
    for i in df.columns:
        if re.findall('person_prefer_._._',i):
            p_cols.append(i)
        if re.findall('contents_attribute_d_.',i):
            c_d_cols.append(i)    
        if re.findall('contents_attribute_h+',i):
            c_h_cols.append(i)
            
    for i in p_cols:
        if i.split('_')[2] == 'd':
            for cols in c_d_cols:
                if i.split('_')[-1] == cols[-1]:
                    df[i[-5:]+'_match_yn'] = (df[i]==df[cols]).astype(int)
        else:
            for cols in c_h_cols:
                if i.split('_')[-1] == cols[-1]:
                    df[i[-5:]+'_match_yn'] = (df[i]==df[cols]).astype(int)
    

    # 선호속성c와 컨텐츠 속성c 일치여부
    df['match_c'] = (df.person_prefer_c==df.contents_attribute_c).astype(int)  
    # 회원선호속성 c는 1~5까지 있는 반면, 컨텐츠 속성c는 1~4만 있음
    # 5 = 무응답이나 기타일것같은.. 없으면 성능 떨어짐
    df['person_prefer_c5'] = (df.person_prefer_c==5).astype(int) 
    
    # 선호속성e와 컨텐츠 속성e 일치여부
    df['match_e'] = (df.person_prefer_e==df.contents_attribute_e).astype(int)
    # person_prefer_e 와 contents_attribute_e차이
    df['differ_e'] = df['person_prefer_e'] - df['contents_attribute_e']
    
    # 순서가 있는 속성
    df = pd.get_dummies(df, columns=['person_attribute_a_1','person_attribute_b','person_prefer_e'])

    #contents_open_dt
    df['contents_open_dt'] = pd.to_datetime(df['contents_open_dt'])
    df['contents_open_hour'] = df['contents_open_dt'].dt.hour
    df['contents_open_day'] = df['contents_open_dt'].dt.dayofweek
    
    if del_columns:
        del_cols += (p_cols + c_d_cols + c_h_cols)
                     
    new_df = df.drop(del_cols, axis=1)
    
    return new_df

In [48]:
train = match_cols(df_train)
test = match_cols(df_test)

In [11]:
train.columns

Index(['d_l_match_yn', 'd_m_match_yn', 'd_s_match_yn', 'h_l_match_yn',
       'h_m_match_yn', 'h_s_match_yn', 'person_prefer_c', 'person_prefer_d_1',
       'person_prefer_d_2', 'person_prefer_d_3',
       ...
       'person_prefer_e_4', 'person_prefer_e_5', 'person_prefer_e_6',
       'person_prefer_e_7', 'person_prefer_e_8', 'person_prefer_e_9',
       'person_prefer_e_10', 'person_prefer_e_11', 'contents_open_hour',
       'contents_open_day'],
      dtype='object', length=104)

In [12]:
test.columns

Index(['d_l_match_yn', 'd_m_match_yn', 'd_s_match_yn', 'h_l_match_yn',
       'h_m_match_yn', 'h_s_match_yn', 'person_prefer_c', 'person_prefer_d_1',
       'person_prefer_d_2', 'person_prefer_d_3',
       ...
       'person_prefer_e_4', 'person_prefer_e_5', 'person_prefer_e_6',
       'person_prefer_e_7', 'person_prefer_e_8', 'person_prefer_e_9',
       'person_prefer_e_10', 'person_prefer_e_11', 'contents_open_hour',
       'contents_open_day'],
      dtype='object', length=103)

# CatBoostClassifier 사용

In [13]:
from catboost import Pool,CatBoostClassifier
import sklearn 
from sklearn.model_selection import StratifiedKFold , KFold
from sklearn.metrics import f1_score

In [49]:
y_train = train['target']
X_train = train.drop(['target'],axis=1)
X_test = test

In [18]:
cat_features = X_train.columns[X_train.nunique() > 2].tolist()
cat_features

['person_prefer_c',
 'person_prefer_d_1',
 'person_prefer_d_2',
 'person_prefer_d_3',
 'person_prefer_h_1',
 'person_prefer_h_2',
 'person_prefer_h_3',
 'contents_attribute_i',
 'contents_attribute_a',
 'contents_attribute_j_1',
 'contents_attribute_c',
 'contents_attribute_l',
 'contents_attribute_d',
 'contents_attribute_m',
 'contents_attribute_e',
 'contents_attribute_h',
 'person_prefer_d_1_n',
 'person_prefer_d_1_s',
 'person_prefer_d_1_m',
 'person_prefer_d_1_l',
 'person_prefer_d_2_n',
 'person_prefer_d_2_s',
 'person_prefer_d_2_m',
 'person_prefer_d_2_l',
 'person_prefer_d_3_n',
 'person_prefer_d_3_s',
 'person_prefer_d_3_m',
 'person_prefer_d_3_l',
 'contents_attribute_d_n',
 'contents_attribute_d_s',
 'contents_attribute_d_m',
 'contents_attribute_d_l',
 'person_prefer_h_1_l',
 'person_prefer_h_1_m',
 'person_prefer_h_2_l',
 'person_prefer_h_2_m',
 'person_prefer_h_3_l',
 'person_prefer_h_3_m',
 'contents_attribute_h_l',
 'contents_attribute_h_m',
 'contents_attribute_l_n',
 'contents_attribute_l_s',
 'contents_attribute_l_m',
 'contents_attribute_l_l',
 'y_km(k5)',
 'differ_e',
 'contents_open_hour',
 'contents_open_day']

In [19]:
cat_features = cat_features[:-5]+ ['y_km(k5)']+ cat_features[-2:] #contents_attribute_l_l, differ_e제외
cat_features

['person_prefer_c',
 'person_prefer_d_1',
 'person_prefer_d_2',
 'person_prefer_d_3',
 'person_prefer_h_1',
 'person_prefer_h_2',
 'person_prefer_h_3',
 'contents_attribute_i',
 'contents_attribute_a',
 'contents_attribute_j_1',
 'contents_attribute_c',
 'contents_attribute_l',
 'contents_attribute_d',
 'contents_attribute_m',
 'contents_attribute_e',
 'contents_attribute_h',
 'person_prefer_d_1_n',
 'person_prefer_d_1_s',
 'person_prefer_d_1_m',
 'person_prefer_d_1_l',
 'person_prefer_d_2_n',
 'person_prefer_d_2_s',
 'person_prefer_d_2_m',
 'person_prefer_d_2_l',
 'person_prefer_d_3_n',
 'person_prefer_d_3_s',
 'person_prefer_d_3_m',
 'person_prefer_d_3_l',
 'contents_attribute_d_n',
 'contents_attribute_d_s',
 'contents_attribute_d_m',
 'contents_attribute_d_l',
 'person_prefer_h_1_l',
 'person_prefer_h_1_m',
 'person_prefer_h_2_l',
 'person_prefer_h_2_m',
 'person_prefer_h_3_l',
 'person_prefer_h_3_m',
 'contents_attribute_h_l',
 'contents_attribute_h_m',
 'contents_attribute_l_n',
 'contents_attribute_l_s',
 'contents_attribute_l_m',
 'y_km(k5)',
 'contents_open_hour',
 'contents_open_day']

In [20]:
len(cat_features)

46

In [21]:
SEED = 42
is_holdout = False
n_splits = 5
iterations = 3000
patience = 100

cv = KFold(n_splits=n_splits, shuffle=True, random_state=SEED)

In [22]:
scores = []
models = []
for tri, vai in cv.split(X_train):
    print("="*50)
    preds = []

    model = CatBoostClassifier(iterations=iterations,random_state=SEED,task_type="CPU",eval_metric="F1",cat_features=cat_features)#,one_hot_max_size=4
    model.fit(X_train.iloc[tri], y_train[tri], 
            eval_set=[(X_train.iloc[vai], y_train[vai])], 
            early_stopping_rounds=patience ,
            verbose = 100
        )
    
    models.append(model)
    scores.append(model.get_best_score()["validation"]["F1"])
    if is_holdout:
        break

==================================================
Learning rate set to 0.086395
0:	learn: 0.6225278	test: 0.6204853	best: 0.6204853 (0)	total: 1.59s	remaining: 1h 19m 23s
100:	learn: 0.6569670	test: 0.6818691	best: 0.6818691 (100)	total: 2m 45s	remaining: 1h 19m 9s
200:	learn: 0.6642253	test: 0.6907625	best: 0.6909270 (197)	total: 5m 45s	remaining: 1h 20m 16s
300:	learn: 0.6683788	test: 0.6925635	best: 0.6925800 (299)	total: 9m 8s	remaining: 1h 22m
400:	learn: 0.6713193	test: 0.6939541	best: 0.6941522 (384)	total: 12m 31s	remaining: 1h 21m 11s
500:	learn: 0.6732086	test: 0.6948271	best: 0.6949702 (488)	total: 15m 57s	remaining: 1h 19m 37s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6949701683
bestIteration = 488

Shrink model to first 489 iterations.
==================================================
Learning rate set to 0.086395
0:	learn: 0.6303790	test: 0.6305194	best: 0.6305194 (0)	total: 1.92s	remaining: 1h 35m 53s
100:	learn: 0.6558846	test: 0.6818657	best: 0.6818657 (100)	total: 3m 29s	remaining: 1h 40m 8s
200:	learn: 0.6637742	test: 0.6883302	best: 0.6883939 (199)	total: 6m 57s	remaining: 1h 36m 49s
300:	learn: 0.6680172	test: 0.6909713	best: 0.6911606 (295)	total: 10m 27s	remaining: 1h 33m 46s
400:	learn: 0.6707754	test: 0.6923787	best: 0.6925727 (366)	total: 13m 54s	remaining: 1h 30m 10s
500:	learn: 0.6731397	test: 0.6932104	best: 0.6934543 (492)	total: 17m 25s	remaining: 1h 26m 53s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6934542977
bestIteration = 492

Shrink model to first 493 iterations.
==================================================
Learning rate set to 0.086395
0:	learn: 0.6086893	test: 0.6088639	best: 0.6088639 (0)	total: 1.98s	remaining: 1h 38m 54s
100:	learn: 0.6585428	test: 0.6801512	best: 0.6804205 (99)	total: 3m 27s	remaining: 1h 39m 8s
200:	learn: 0.6656671	test: 0.6866207	best: 0.6866207 (200)	total: 6m 41s	remaining: 1h 33m 9s
300:	learn: 0.6694444	test: 0.6885579	best: 0.6887777 (295)	total: 10m 15s	remaining: 1h 31m 57s
400:	learn: 0.6721283	test: 0.6889752	best: 0.6890377 (397)	total: 13m 36s	remaining: 1h 28m 10s
500:	learn: 0.6744035	test: 0.6904898	best: 0.6906324 (490)	total: 17m 5s	remaining: 1h 25m 15s
600:	learn: 0.6757253	test: 0.6905296	best: 0.6910024 (580)	total: 20m 26s	remaining: 1h 21m 35s
700:	learn: 0.6777355	test: 0.6911763	best: 0.6913949 (684)	total: 23m 48s	remaining: 1h 18m 6s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6913948536
bestIteration = 684

Shrink model to first 685 iterations.
==================================================
Learning rate set to 0.086395
0:	learn: 0.6279485	test: 0.6257638	best: 0.6257638 (0)	total: 1.18s	remaining: 59m 3s
100:	learn: 0.6580074	test: 0.6790224	best: 0.6791641 (98)	total: 2m 44s	remaining: 1h 18m 43s
200:	learn: 0.6646841	test: 0.6856448	best: 0.6856448 (200)	total: 5m 28s	remaining: 1h 16m 10s
300:	learn: 0.6691850	test: 0.6892032	best: 0.6893382 (291)	total: 8m 17s	remaining: 1h 14m 21s
400:	learn: 0.6718107	test: 0.6900308	best: 0.6900540 (397)	total: 11m 3s	remaining: 1h 11m 39s
500:	learn: 0.6737989	test: 0.6899752	best: 0.6901314 (462)	total: 13m 47s	remaining: 1h 8m 48s
600:	learn: 0.6753502	test: 0.6906361	best: 0.6906892 (582)	total: 16m 33s	remaining: 1h 6m 7s
700:	learn: 0.6764311	test: 0.6902212	best: 0.6907655 (620)	total: 19m 20s	remaining: 1h 3m 24s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6907654636
bestIteration = 620

Shrink model to first 621 iterations.
==================================================
Learning rate set to 0.086395
0:	learn: 0.6272348	test: 0.6258206	best: 0.6258206 (0)	total: 1.34s	remaining: 1h 6m 58s
100:	learn: 0.6581279	test: 0.6784286	best: 0.6784286 (100)	total: 2m 53s	remaining: 1h 22m 51s
200:	learn: 0.6651332	test: 0.6840614	best: 0.6842606 (196)	total: 6m 26s	remaining: 1h 29m 36s
300:	learn: 0.6697186	test: 0.6867223	best: 0.6871603 (289)	total: 10m 9s	remaining: 1h 31m 2s
400:	learn: 0.6723905	test: 0.6879395	best: 0.6880466 (350)	total: 13m 44s	remaining: 1h 29m 1s
500:	learn: 0.6743257	test: 0.6876245	best: 0.6880633 (401)	total: 17m 42s	remaining: 1h 28m 21s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6880633271
bestIteration = 401

Shrink model to first 402 iterations.

In [23]:
print(scores)
print(np.mean(scores))

[0.6949701683457671, 0.69345429768805, 0.6913948536102591, 0.690765463603186, 0.6880633271119198]
0.6917296220718364

* k5, l 모두 제외했을 때 0.69155
* k5, l 대분류만 제외했을 때 0.6917399210868103
* k3, l 대분류만 제외했을 때 0.6916203017590643
* 추가된 조합 feature 없애고 k3 0.6911727399167477
* 추가된 조합 feature 없애고 k5

In [50]:
threshold = 0.4
pred_list = []
scores = []
for i,(tri, vai) in enumerate( cv.split(X_train) ):
    pred = models[i].predict_proba(X_train.iloc[vai])[:, 1]
    pred = np.where(pred >= threshold , 1, 0)
    score = f1_score(y_train[vai],pred)
    scores.append(score)
    pred = models[i].predict_proba(X_test)[:, 1]
    pred_list.append(pred)
print(scores)
print(np.mean(scores))

[0.715902081101263, 0.7151428664093665, 0.7148811223033318, 0.7153819181120598, 0.7126042496464047]
0.7147824475144852

In [52]:
pred = np.mean( pred_list , axis = 0 )
pred = np.where(pred >= threshold , 1, 0)

In [53]:
submission = pd.read_csv('./_data/sample_submission.csv')
submission.head()

   id  target
0   0       0
1   1       0
2   2       0
3   3       0
4   4       0

In [54]:
submission['target'] = pred
submission

          id  target
0          0       0
1          1       0
2          2       0
3          3       0
4          4       0
...      ...     ...
46399  46399       1
46400  46400       1
46401  46401       1
46402  46402       1
46403  46403       1

[46404 rows x 2 columns]

In [55]:
submission.to_csv('./submission17.csv', index=False)

# PUBLIC 0.7004061565